Update project to use loopback-3.x
strongloop/loopback-sdk-ios pull request #125
Opened 2016-09-23 20:52 UTC by gunjpan

Update to use `loopback-3.x` and `strong-remoting 3.x`

2016-11-29 16:51 UTC, gunjpan commented
**Update 29/11**
- Blocked until new version of `strong-remoting` is released to npmjs.org

2016-12-13 15:48 UTC, bajtos requested changes

2016-12-13 15:48 UTC, bajtos commented on LoopBackTests/server/index.js
> +app.dataSource('Memory', { connector: 'memory' });
nitpick (feel free to ignore): we usually use `db` as the name of the main datasource.

2016-12-13 15:48 UTC, bajtos commented on LoopBackTests/server/index.js
> +  http: { verb: 'get', source: 'form'}
AFAIK, the `GET` method explicitly forbids non-empty request bodies, therefore there will be no `form` to get the value from.

I assume the tests are passing for you, which may mean that `source: 'form'` is ignored, or that the test is sending a `GET` request with a non-empty body. Could you please investigate?

2016-12-13 15:48 UTC, bajtos commented on LoopBackTests/server/index.js
> +app.model(loopback.AccessToken, {dataSource: 'Memory'});
This should be automatically handled by `app.enableAuth({ dataSource: 'Memory' });`.

2016-12-13 15:48 UTC, bajtos commented on LoopBackTests/server/index.js
> +app.dataSource('mail', { connector: 'mail' });
Since we are not calling `autoAttach`, the `mail` datasource should not be needed at all now.

2016-12-13 15:48 UTC, bajtos commented on SLRemoting/SLObject.m
> +            value = jsonString ;
Is there a way how to support both LB2.x and LB3.x servers with a single SDK client? I am concerned that with this change in place, users won't be able to use the latest SDK version with their LB2.x apps.

Also I don't recall changing the format of date arguments in strong-remoting, why is this fix needed in the first place? Is this perhaps a side-effect of my coercion refactor that I did not discover?

2016-12-13 15:51 UTC, gunjpan commented on LoopBackTests/server/index.js
> +app.dataSource('Memory', { connector: 'memory' });
Yes, it occurred to me but kept as is to be in sync with existing code

2016-12-13 16:07 UTC, gunjpan commented on SLRemoting/SLObject.m
> +            value = jsonString ;
>Is this perhaps a side-effect of my coercion refactor that I did not discover?

There was some coercion issue, don't remember ATM. Will update you with the findings.

2016-12-13 17:05 UTC, gunjpan commented on SLRemoting/SLObject.m
> +            value = jsonString ;
@bajtos :
Update: 
` value = @{ @"$type": @"date", @"$data": jsonString };`

gets converted to following URL string, which is not coerced correctly 
`http://localhost:3000/widgets/testDate?date[%24data]=1970-01-01T00%3A02%3A03.000Z&date[%24type]=date`

2016-12-14 14:21 UTC, bajtos commented on LoopBackTests/server/index.js
> +app.dataSource('Memory', { connector: 'memory' });
Fair enough.

2016-12-14 14:25 UTC, bajtos commented on SLRemoting/SLObject.m
> +            value = jsonString ;
I see. Could you please check what happens when you use the new simplified encoding `testDate?date=1970-01-01T00%3A02%3A03.000Z` when calling a LoopBack 2.x server? Will the server correctly convert the value to a Date instance?

I think this is a subtle but also an important breaking change, could you please add a note to both Release Notes and Migration Guide for 3.0?

2016-12-16 19:17 UTC, rmg commented
@slnode test please

2016-12-27 16:33 UTC, gunjpan commented
@slnode test please

2017-01-02 15:51 UTC, bajtos commented on SLRemoting/SLObject.m
> +            value = jsonString ;
> I think this is a subtle but also an important breaking change, could you please add a note to both Release Notes and Migration Guide for 3.0?

I mean that Release Notes should mention that LoopBack 3.x not longer recognizes nested query arguments encoded using `{$type,$data}` schema and show what's the new format. The Migration Guide should have a short section telling users to upgrade their client apps.

2017-01-02 15:52 UTC, bajtos commented
> Could you please check what happens when you use the new simplified encoding `testDate?date=1970-01-01T00%3A02%3A03.000Z` when calling a LoopBack 2.x server? Will the server correctly convert the value to a Date instance?

@gunjpan have you managed to trie the above? What was the result?

2017-01-03 14:13 UTC, gunjpan commented
@bajtos : 
>I see. Could you please check what happens when you use the new simplified encoding testDate?date=1970-01-01T00%3A02%3A03.000Z when calling a LoopBack 2.x server? Will the server correctly convert the value to a Date instance?

It worked fine for LB 2.x server, IIRC, it converts the value to Date instance, need to verify one more time.

2017-12-01 17:33 UTC, igordeoliveirasa commented
any news? i'd like to use your version @gunjpan

2018-01-05 09:27 UTC, bajtos commented
@igordeoliveirasa I am afraid we are no longer actively maintaining the project. Would you perhaps like to step up to become a maintainer yourself? If yes, then please leave a comment in https://github.com/strongloop-community/loopback-sdk-ios/issues/136

2020-05-15 09:51 UTC, closed without merging